# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='grpc_wrappers.tests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rexample.proto\x12\x13grpc_wrappers.tests\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xbe\x05\n\x0e\x45xampleMessage\x12\x12\n\nbool_value\x18\x01 \x01(\x08\x12\x11\n\tint_value\x18\x02 \x01(\x03\x12\x14\n\x0cstring_value\x18\x03 \x01(\t\x12\x34\n\nenum_value\x18\x04 \x01(\x0e\x32 .grpc_wrappers.tests.ExampleEnum\x12\x37\n\nsubmessage\x18\x05 \x01(\x0b\x32#.grpc_wrappers.tests.ExampleMessage\x12#\n\x17\x64\x65precated_string_value\x18\x06 \x01(\tB\x02\x18\x01\x12\x12\n\nint_values\x18\x07 \x03(\x03\x12\x35\n\x0b\x65num_values\x18\x08 \x03(\x0e\x32 .grpc_wrappers.tests.ExampleEnum\x12\x38\n\x0bsubmessages\x18\t \x03(\x0b\x32#.grpc_wrappers.tests.ExampleMessage\x12L\n\x11nested_submessage\x18\n \x01(\x0b\x32\x31.grpc_wrappers.tests.ExampleMessage.NestedMessage\x12\x36\n\x12wrapped_bool_value\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x38\n\x13wrapped_float_value\x18\x0c \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12:\n\x14wrapped_string_value\x18\r \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x11wrapped_timestamp\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a#\n\rNestedMessage\x12\x12\n\nbool_value\x18\x01 \x01(\x08*0\n\x0b\x45xampleEnum\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x12\x05\n\x01\x43\x10\x02\x12\x05\n\x01\x44\x10\x03\x12\x05\n\x01\x45\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])

_EXAMPLEENUM = _descriptor.EnumDescriptor(
  name='ExampleEnum',
  full_name='grpc_wrappers.tests.ExampleEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='A', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='B', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=808,
  serialized_end=856,
)
_sym_db.RegisterEnumDescriptor(_EXAMPLEENUM)

ExampleEnum = enum_type_wrapper.EnumTypeWrapper(_EXAMPLEENUM)
A = 0
B = 1
C = 2
D = 3
E = 4



_EXAMPLEMESSAGE_NESTEDMESSAGE = _descriptor.Descriptor(
  name='NestedMessage',
  full_name='grpc_wrappers.tests.ExampleMessage.NestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='grpc_wrappers.tests.ExampleMessage.NestedMessage.bool_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=771,
  serialized_end=806,
)

_EXAMPLEMESSAGE = _descriptor.Descriptor(
  name='ExampleMessage',
  full_name='grpc_wrappers.tests.ExampleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='grpc_wrappers.tests.ExampleMessage.bool_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='grpc_wrappers.tests.ExampleMessage.int_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='grpc_wrappers.tests.ExampleMessage.string_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_value', full_name='grpc_wrappers.tests.ExampleMessage.enum_value', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='submessage', full_name='grpc_wrappers.tests.ExampleMessage.submessage', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deprecated_string_value', full_name='grpc_wrappers.tests.ExampleMessage.deprecated_string_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_values', full_name='grpc_wrappers.tests.ExampleMessage.int_values', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_values', full_name='grpc_wrappers.tests.ExampleMessage.enum_values', index=7,
      number=8, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='submessages', full_name='grpc_wrappers.tests.ExampleMessage.submessages', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested_submessage', full_name='grpc_wrappers.tests.ExampleMessage.nested_submessage', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrapped_bool_value', full_name='grpc_wrappers.tests.ExampleMessage.wrapped_bool_value', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrapped_float_value', full_name='grpc_wrappers.tests.ExampleMessage.wrapped_float_value', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrapped_string_value', full_name='grpc_wrappers.tests.ExampleMessage.wrapped_string_value', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrapped_timestamp', full_name='grpc_wrappers.tests.ExampleMessage.wrapped_timestamp', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EXAMPLEMESSAGE_NESTEDMESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=806,
)

_EXAMPLEMESSAGE_NESTEDMESSAGE.containing_type = _EXAMPLEMESSAGE
_EXAMPLEMESSAGE.fields_by_name['enum_value'].enum_type = _EXAMPLEENUM
_EXAMPLEMESSAGE.fields_by_name['submessage'].message_type = _EXAMPLEMESSAGE
_EXAMPLEMESSAGE.fields_by_name['enum_values'].enum_type = _EXAMPLEENUM
_EXAMPLEMESSAGE.fields_by_name['submessages'].message_type = _EXAMPLEMESSAGE
_EXAMPLEMESSAGE.fields_by_name['nested_submessage'].message_type = _EXAMPLEMESSAGE_NESTEDMESSAGE
_EXAMPLEMESSAGE.fields_by_name['wrapped_bool_value'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_EXAMPLEMESSAGE.fields_by_name['wrapped_float_value'].message_type = google_dot_protobuf_dot_wrappers__pb2._FLOATVALUE
_EXAMPLEMESSAGE.fields_by_name['wrapped_string_value'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_EXAMPLEMESSAGE.fields_by_name['wrapped_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ExampleMessage'] = _EXAMPLEMESSAGE
DESCRIPTOR.enum_types_by_name['ExampleEnum'] = _EXAMPLEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleMessage = _reflection.GeneratedProtocolMessageType('ExampleMessage', (_message.Message,), dict(

  NestedMessage = _reflection.GeneratedProtocolMessageType('NestedMessage', (_message.Message,), dict(
    DESCRIPTOR = _EXAMPLEMESSAGE_NESTEDMESSAGE,
    __module__ = 'example_pb2'
    # @@protoc_insertion_point(class_scope:grpc_wrappers.tests.ExampleMessage.NestedMessage)
    ))
  ,
  DESCRIPTOR = _EXAMPLEMESSAGE,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:grpc_wrappers.tests.ExampleMessage)
  ))
_sym_db.RegisterMessage(ExampleMessage)
_sym_db.RegisterMessage(ExampleMessage.NestedMessage)


_EXAMPLEMESSAGE.fields_by_name['deprecated_string_value']._options = None
# @@protoc_insertion_point(module_scope)
